---
title: "College Football Games and Crimes"
author: "Nabin Oli & Nava Nizard"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: yes
        toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE
)
library(cfbfastR)
library(tidyverse)
library(lubridate)
library(stringr)
```

## Data Extraction & Wrangling
### College Football Data Extraction
```{r import-cfb-data, results='hide'}
# Pull schedule data from espn_cfb_schedule function
years = c(2000:2005)
data_func <- function(years) {
    espn_cfb_schedule(year = years)
}
schedule <- map_dfr(years, data_func)
```

### Crime Data Extraction
```{r import-crime-data, results='hide'}
colleges <- read_csv("colleges.csv")
offenses <- read_csv("offenses.csv")
unfiltered_ori_and_team_names <- read_csv("unfiltered_ori_and_team_names.csv", col_names = c("ori", "team_name"))
```

### Filter Crime Data & College Data
```{r filter-colleges, results='hide'}
# Crime Data
# only select certain columns
offenses <- offenses %>%
    select(ori,
           state_abb,
           incident_date,
           ucr_offense_code)

# add a field to identify the offense type
offenses <- offenses %>%
    mutate(offense_type = case_when(str_detect(ucr_offense_code, pattern = paste("assault")) ~ "assault",
                                    str_detect(ucr_offense_code, pattern = paste("vandalism")) ~ "vandalism")) %>%
    select(-ucr_offense_code)
# College Data 
# only from our 26 schools/teams
filtered_schedule <- schedule %>%
    filter(home_team_full %in% colleges$NCAA_Team | 
           away_team_full %in% colleges$NCAA_Team)

filtered_schedule <- filtered_schedule %>% 
    select(game_id,
           game_date,
           home_team_full,
           home_team_name,
           away_team_full,
           away_team_name,
           home_win,
           away_win)
```

### Remove Duplicate ORIs
```{r deciding-duplicate-ORIs, results='hide'}
# Names of teams that have > 1 ORI value
duplicate_team_names <- unfiltered_ori_and_team_names %>%
    group_by(team_name) %>%
    summarise(count = n()) %>%
    filter(count > 1)%>%
    select(team_name)

# Names and ORIs of teams that have > 1 ORI value
duplicate_ori <- unfiltered_ori_and_team_names %>%
    filter(team_name %in% duplicate_team_names$team_name) 

# ORIs of teams that have > 1 ORI value with the associated number of offenses
offense_counts_by_duplicate_ori <- offenses %>% 
    filter(ori %in% duplicate_ori$ori)%>%
    group_by(ori)%>%
    summarise(count = n())

# Choose the ORI value with the highest number of offenses
filtered_duplicates <- full_join(offense_counts_by_duplicate_ori, duplicate_ori, by = 'ori') %>%
    filter(is.na(count) == FALSE) %>% # The NA values mean there're no offenses associated with that ORI
    group_by(team_name) %>% 
    filter(count == max(count))

# Create a new CSV file with no duplicates
unfiltered_ori_and_team_names %>%
    filter(!(ori %in% duplicate_ori$ori) | (ori %in% filtered_duplicates$ori) ) %>%  # Keep rows who don't have duplicates + Add the filtered duplicates
    write_csv("ori_and_team_names.csv")

# importing our ori and team mapping
ori_and_team_names <- read_csv("ori_and_team_names.csv")

# filter offense data with new requirements
offenses <- offenses %>%
            filter(is.na(offense_type)==FALSE) #filtering offences where type == NA
offenses <- offenses %>%
    filter(ori %in% ori_and_team_names$ori) %>% # filter out duplicate ori offenses
    group_by(ori, incident_date, offense_type) %>% # find count of assault and vandalism for each day and ori combo
    summarize(count = n()) %>%
    pivot_wider(names_from = offense_type, values_from = count, values_fill = 0) # get columns for assault and vandalism counts

```

### Join Crime and College Football Data
```{r joining-crime-and-cfb, results='hide'}
# restructure data to have 1 column with the team name
filtered_schedule_long <- filtered_schedule %>% 
    rename(home_team = "home_team_full", away_team = "away_team_full") %>% # to simplify the values in home_or_away
    pivot_longer(names_to = 'home_or_away',
                 values_to = "team_name",
                 cols = c(home_team, away_team))

# attach ORIs to the game data
schedule_with_ori <- full_join(filtered_schedule_long, ori_and_team_names, by = "team_name") %>%
    filter(is.na(ori) == FALSE) %>% # filter out the rows where teams aren't on our list
    rename(incident_date = "game_date") # rename to join

# checking for duplicates in our schedlue data
duplicates <- schedule_with_ori%>%
    group_by(incident_date,ori) %>%
    summarise(count = n()) %>%
    filter(count != 1)%>%select(-count)

#creating duplicates that needed to be removed    
duplicate_table <- inner_join(duplicates,schedule_with_ori) %>%
    filter(home_team_name %in% c("Fighting Illini","Falcons","Hokies")==FALSE) #those were fake entries

#filtering those duplicates form our schedule data frame 
schedule_with_ori <- anti_join(schedule_with_ori,duplicate_table,
        by = c("incident_date",
        "game_id",
        "home_team_name",
        "away_team_name","ori")) #removing entries that are in duplicates from schedule_with_ori table

# join the cfb and offenses data on ORI and date
test_frame <- full_join(offenses, schedule_with_ori, by = c('ori','incident_date')) %>%
    mutate(game_status = case_when((is.na(ori) == FALSE) & (home_or_away == "home_team") ~ "home_game", 
                                   (is.na(ori) == FALSE) & (home_or_away == "away_team") ~ "away_game",
                                    is.na(game_id) ~ "no_game"))

```

### Template Table and Final dataframe creation
```{r template table and final dataframe creation}
# Here we are creating our final dataframe and populating them with dates and ori combination
year=c(2000:2005) # gets the array from 2000 to 2005
#creating a function to create a dataframe with dates
table_func <- function(years) {
            data.frame(day = seq(as.Date(paste0(years,"-08-20")),
            as.Date(paste0(years,"-12-10")),
            by = 'day'))
}
#assembling all dates dataframe into one table
dates_table <- map_dfr(year, table_func)

# Our table with all entries of date and ori
template_table <- expand_grid(dates_table,ori_and_team_names$ori) %>%
                  rename(ori = "ori_and_team_names$ori")# renaming for joining purpose

test_frame <- rename(test_frame,day = incident_date) # renaming for joining purpose
# Final table with all entries
final_table <- left_join(template_table,test_frame,by=c("day","ori")) %>%
                        replace_na(list(assault = 0,vandalism = 0)) #filling in zeros for NA's
```

## Table 2: Distribution of Game Days by Day of the Week
```{r replicate-table-2}
# Calculate number of games per day of the week
num_of_games_per_dotw <- filtered_schedule %>% 
    mutate(day_of_the_week = wday(game_date, label = TRUE)) %>%
    group_by(day_of_the_week) %>%
    summarize(num_of_games = n())

# Calculate number of {DOTW} observered over the cfb season over 2000-2005 for all ORIs
num_of_observatiions_per_dotw <- template_table %>% # about 13 (num of {DOTW}) * 6 (years) * 26 (ORIs / num of agencies)
    mutate(day_of_the_week = wday(game_date, label = TRUE)) %>%
    group_by(day_of_the_week, ori) %>%
    summarize(num_of_oberservations = n())
    
# Merge results
joined_tbl <- full_join(num_of_games_per_dotw, num_of_observations_per_dotw, by = "day_of_the_week")

# Add totals row
totals_row <- tibble(
  day_of_the_week = "Total",
  num_of_games = sum(joined_tbl$num_of_games),
  num_of_offenses = sum(joined_tbl$num_of_observations))

tbl2 <- bind_rows(joined_tbl, totals_row) # Append totals

tbl2 # display table
```

## Distribution of Offenses on Saturdays
```{r distribution-of-offenses-on-saturdays, results='hide'}
# Create figures showing the mean number of offenses (assaults or vandalisms) on Saturdays 
# (with standard errors), broken out by whether a home game, away game, 
# or no game was played. 

```